name: hw3-stack
version: 0.1.0.0
github: "githubuser/hw3-stack"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/hw3-stack#readme>

dependencies:
  - base >= 4.7 && < 5
  - megaparsec
  - deepseq
  - text
  - scientific == 0.3.7.0
  - mtl
  - prettyprinter
  - prettyprinter-ansi-terminal
  - haskeline
  - parser-combinators

library:
  source-dirs: src

executables:
  hw3-stack-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hw3-stack
      - megaparsec
      - text
      - scientific == 0.3.7.0
      - mtl
      - prettyprinter
      - prettyprinter-ansi-terminal
      - haskeline
      - parser-combinators

tests:
  hw3-stack-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      # - hw3-stack
      - megaparsec
